// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foodSearch,
    foods,
    foodsSearchInsert,
    foodsSearchUpdate,
    foodsSearchDelete,
    measures,
    assetVersions,
    diaryItems,
    planItems,
    planChecks,
    bodyMeasurements,
    profiles,
    favorites,
    settings,
    foodsBySource,
    measuresByFood,
    diaryItemsByDay,
    diaryItemsByFood,
    planItemsByMeal,
    bodyMeasurementsByDate,
  ];
  late final Shape0 foodSearch = Shape0(
    source: i0.VersionedVirtualTable(
      entityName: 'food_search',
      moduleAndArgs: 'fts5(food_id UNINDEXED, body, tokenize = \'unicode61 remove_diacritics 2\')',
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foods = Shape1(
    source: i0.VersionedTable(
      entityName: 'foods',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger foodsSearchInsert = i1.Trigger(
    'CREATE TRIGGER foods_search_insert AFTER INSERT ON foods BEGIN INSERT INTO food_search (food_id, body) VALUES (new.id, new.search_text);END',
    'foods_search_insert',
  );
  final i1.Trigger foodsSearchUpdate = i1.Trigger(
    'CREATE TRIGGER foods_search_update AFTER UPDATE OF search_text ON foods BEGIN DELETE FROM food_search WHERE food_id = old.id;INSERT INTO food_search (food_id, body) VALUES (new.id, new.search_text);END',
    'foods_search_update',
  );
  final i1.Trigger foodsSearchDelete = i1.Trigger(
    'CREATE TRIGGER foods_search_delete AFTER DELETE ON foods BEGIN DELETE FROM food_search WHERE food_id = old.id;END',
    'foods_search_delete',
  );
  late final Shape2 measures = Shape2(
    source: i0.VersionedTable(
      entityName: 'measures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_2,
        _column_16,
        _column_3,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 assetVersions = Shape3(
    source: i0.VersionedTable(
      entityName: 'asset_versions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(asset)'],
      columns: [_column_21, _column_22, _column_23, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 diaryItems = Shape4(
    source: i0.VersionedTable(
      entityName: 'diary_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_2,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_18,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 planItems = Shape5(
    source: i0.VersionedTable(
      entityName: 'plan_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_2,
        _column_26,
        _column_27,
        _column_16,
        _column_30,
        _column_31,
        _column_32,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 planChecks = Shape6(
    source: i0.VersionedTable(
      entityName: 'plan_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(date, meal)'],
      columns: [_column_25, _column_26, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 bodyMeasurements = Shape7(
    source: i0.VersionedTable(
      entityName: 'body_measurements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_2,
        _column_25,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 profiles = Shape8(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_46,
        _column_5,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 favorites = Shape9(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(food_id)'],
      columns: [_column_16, _column_39],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_53, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodsBySource = i1.Index(
    'foods_by_source',
    'CREATE INDEX foods_by_source ON foods (source, is_active)',
  );
  final i1.Index measuresByFood = i1.Index(
    'measures_by_food',
    'CREATE INDEX measures_by_food ON measures (food_id)',
  );
  final i1.Index diaryItemsByDay = i1.Index(
    'diary_items_by_day',
    'CREATE INDEX diary_items_by_day ON diary_items (date, meal, position)',
  );
  final i1.Index diaryItemsByFood = i1.Index(
    'diary_items_by_food',
    'CREATE INDEX diary_items_by_food ON diary_items (food_id)',
  );
  final i1.Index planItemsByMeal = i1.Index(
    'plan_items_by_meal',
    'CREATE INDEX plan_items_by_meal ON plan_items (meal, position)',
  );
  final i1.Index bodyMeasurementsByDate = i1.Index(
    'body_measurements_by_date',
    'CREATE INDEX body_measurements_by_date ON body_measurements (date)',
  );
}

class Shape0 extends i0.VersionedVirtualTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get tacoNumber =>
      columnsByName['taco_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchText =>
      columnsByName['search_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get kcal =>
      columnsByName['kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carb =>
      columnsByName['carb']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fat =>
      columnsByName['fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fiber =>
      columnsByName['fiber']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sodium =>
      columnsByName['sodium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get nutrientsJson =>
      columnsByName['nutrients_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'taco_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'kcal',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carb',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fiber',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sodium',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nutrients_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get grams =>
      columnsByName['grams']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get reference =>
      columnsByName['reference']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES foods(id)',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grams',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reference',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get asset =>
      columnsByName['asset']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get itemCount =>
      columnsByName['item_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get importedAt =>
      columnsByName['imported_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'asset',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'item_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'imported_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodName =>
      columnsByName['food_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get measureLabel =>
      columnsByName['measure_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get measureGrams =>
      columnsByName['measure_grams']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get grams =>
      columnsByName['grams']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get kcal100 =>
      columnsByName['kcal100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein100 =>
      columnsByName['protein100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carb100 =>
      columnsByName['carb100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fat100 =>
      columnsByName['fat100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fiber100 =>
      columnsByName['fiber100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sodium100 =>
      columnsByName['sodium100']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'measure_label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'measure_grams',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'kcal100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_34(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_35(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carb100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fiber100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sodium100',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get measureLabel =>
      columnsByName['measure_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get measureGrams =>
      columnsByName['measure_grams']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get grams =>
      columnsByName['grams']! as i1.GeneratedColumn<double>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get checkedAt =>
      columnsByName['checked_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'checked_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get waistCm =>
      columnsByName['waist_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get neckCm =>
      columnsByName['neck_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get hipCm =>
      columnsByName['hip_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_42(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'waist_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'neck_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'hip_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get birthDate =>
      columnsByName['birth_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get heightCm =>
      columnsByName['height_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get goal =>
      columnsByName['goal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get activity =>
      columnsByName['activity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get manualKcalTarget =>
      columnsByName['manual_kcal_target']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'birth_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sex',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_49(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'height_cm',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'goal',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_52(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'manual_kcal_target',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
